name: actions

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: |
          make lint
      - name: Run Tests
        run: |
          make test
      - name:  Coverage report
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: 9491c98809ddf0e9970dd4e134cf0474acb03040da34de0c1f72ed8741e7adf3
        with:
          coverageCommand: make coverage